### ISSUE TITLE
Referring to commands from other Actuator Profiles

### ISSUE THREAD

**Issue by MartinEvandt** [oasis-tcs/openc2-ap-edr#14]
EDR systems often either incorporate functionalities of, or interface with, security components that are covered by Actuator Profiles other than EDR - for example AV \[1\] functionalities or Firewalls \[2\] functionalities.  How would we go about referring to commands that are applicable to one AP, but are already defined in other APs?

Currently the ER Targets section has a subsection named [External Namespace Targets](https://github.com/MartinEvandt/openc2-ap-edr/blob/working/oc2edr.md#2123-external-namespace-targets) (which is a very vague and non-descript title), in which table 2.1.2-3 lists the "Stateless Packet Filter Targets Applicable to ER". The idea here was to include the action-target pairs into the AP in the same way that actions and targets from the LS are included in one separate section, and Targets (and any Actions) unique to EDR are written in a another separate section.

![image](https://user-images.githubusercontent.com/19354490/117980295-1c55fa00-b334-11eb-9b17-407a0b10ecd2.png)

The way I see this, this will lead to redundant Actions and Targets being included (the Deny Action as well as the IPv4/IPv6 Net Targets are already included in the AP for other Commands), bloating the AP. My suggestions are:

1. Have a section of the AP which explains unequivocally that certain Commands (and by extensions Actions, Targets and Arguments) are defined in a separate AP, listing the Commands and linking to them.
2.  Do it like we do with LS Actions/Targets/Arguments and include all of them in their own separate "\<External AP\> Actions/Targets/Command Arguments applicable to \<AP\>" sections.
3. Have a separate Command Matrix for the external Commands, so as to clearly separate them from the "native" action-target pairs.
4. Separate duplicate Actions and Targets by their namespace in the command matrix to denote that their action-target pair/Command is defined elsewhere: 
   | |ipv4_net|slpf:ipv4_net|File |
   |:---|:---:|:---:|:---:|
   | **deny** 		     |     |     |valid|
   | **slpf:deny**      |     |valid|     |
   | **set** 		     |valid|     |     |
   
    And then describe the command separately in section 2.3 (i.e., "slpf:deny slpf:ipv4 net"), where we refer to the SLPF AP
5. Some combination of the above

Further, the SLPF Commands and conformances are mentioned in Sections 2.3 (Ex: [2.3.2.2 slpf:Deny ipv4 net](https://github.com/oasis-tcs/openc2-ap-edr/blob/working/oc2edr.md#2322-slpfdeny-ipv4-net)) and 3.1 and 3.2 (Ex: [3.1.8 Conformance Clause 8: Allow/Deny IPv4 Net Producer](https://github.com/oasis-tcs/openc2-ap-edr/blob/working/oc2edr.md#318-conformance-clause-8-allowdeny-ipv4-net-producer)).  These simply state 

> "Must be implemented in accordance with SLPF Allow Command as well as the SLPF Conformance Statements."

 and 

> "MUST meet all of conformance criteria identified in Conformance Clause 1 of the conformance section of the Stateless Packet Filter specification."

 respectively. Both of which link to the relevant resource(s) on the SLPF github (this link will be changed to the official specification on the OASIS website shortly). Is this language too diffuse? If so, what should the standard wording be?

Lastly, right now the EDR AP has [normative references](https://github.com/oasis-tcs/openc2-ap-edr/blob/working/oc2edr.md#13-normative-references) to each SLPF Command that is applicable to EDR, as well as the conformance section of the SLPF AP, and are cited where applicable. Should this be done that way, or should we only include a single reference to the SLPF AP?

\[1\]: https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/why-use-microsoft-defender-antivirus
\[2\]: https://www.crowdstrike.com/press-releases/crowdstrike-expands-cloud-native-falcon-platform-with-new-firewall-management-module/

**Comment by dlemire60** [comment]
My thoughts:

1. I like option 4 for documenting where external actions & targets are defined. That way the table in the EDR spec is a concise definition of the scope of EDR functionality that also clearly distinguishes between "native" and "imported" functionality.
2. I believe our normative and informative references need to be to documents, not paragraphs within documents. Put the details of where within the document is of concern where the refence is invoked (e.g., SLPF AP, Section blah-de-blah). This approach matters more the more distinct locations are targeted in a referenced document, otherwise you wind up with _n_ references to the same document, different locations in your normative references list.
3. I'd like to handle conformance with some blanket statement invoking the conformance clauses of the referenced APs. 

Observation:  This is developing into a fairly high degree of interconnection and cross-referencing among our documents, with conformance implications.  I'm wondering if getting some guidance from the OASIS Technical Advisory Board (TAB) would be appropriate.  @TobyConsidine -- any thoughts on that?

**Comment by MartinEvandt** [comment]
Closing this as it isn't an issue anymore after PR #38.
